In [213]:
# import os
# import cv2
# path = "./DB4_B_2000"
# objects = os.listdir(path)
# files_file = [f for f in objects if os.path.isfile(os.path.join(path, f))]

In [214]:
# for file in files_file:
#     img = cv2.imread("./DB4_B_2000/"+file, 0)
#     img_resize = cv2.resize(img ,(288,384))
#     cv2.imwrite("./DB4_B_2000_resize/"+file, img_resize)

In [215]:
# import os
# import cv2
# path = "./DB4_B_2000_resize"
# objects = os.listdir(path)
# files_file = [f for f in objects if os.path.isfile(os.path.join(path, f))]

In [216]:
# list_shape_2000 = []
# for file in files_file:
#     img = cv2.imread("./DB4_B_2000_resize/"+file, 0)
#     list_shape_2000.append(img.shape)

In [217]:
# set(list_shape_2000)

In [218]:
# path = "./DB4_B_2004"
# objects = os.listdir(path)
# files_file = [f for f in objects if os.path.isfile(os.path.join(path, f))]

In [219]:
# list_shape_2004 = []
# for file in files_file:
#     img = cv2.imread("./DB4_B_2004/"+file, 0)
#     list_shape_2004.append(img.shape)

In [220]:
# set(list_shape_2004)

In [221]:
import cv2
import fingerprint_enhancer
import fingerprint_feature_extractor
import numpy as np
from matching import extract_angle, extract_tuple_profile, generate_tuple_profile, match_tuples, similarity_two_img
import json

In [222]:
img1 = cv2.imread('./DB4_B_2000/106_1.tif',0)
img2 = cv2.imread('./DB4_B_2000/106_2.tif',0)

In [223]:
out1 = fingerprint_enhancer.enhance_Fingerprint(img1)
out2 = fingerprint_enhancer.enhance_Fingerprint(img2)

In [224]:

FeaturesTerm1, FeaturesBif1 = fingerprint_feature_extractor.extract_minutiae_features(out1, showResult= False)
FeaturesTerm2, FeaturesBif2 = fingerprint_feature_extractor.extract_minutiae_features(out2, showResult= False)

In [225]:
len1 = FeaturesTerm1 + FeaturesBif1
len2 = FeaturesTerm2 + FeaturesBif2

In [226]:
list_minutiae1 = []
for i in range(len(len1)):
    list_minutiae1.append((len1[i].locX, len1[i].locY))
    

In [227]:
list_minutiae2 = []
for i in range(len(len2)):
    list_minutiae2.append((len2[i].locX, len2[i].locY))

In [228]:
feature1 = generate_tuple_profile(list_minutiae1,7)
feature2 = generate_tuple_profile(list_minutiae2,7)

In [229]:
ratios_test = np.array([ratios for c, [ratios, _] in feature2.items()])
angles_test = np.array([angles for c, [_, angles] in feature2.items()])


In [230]:
aa =[ 28.73,  33.76,  71.79, 154.75,  44.38,  70.73,   5.03,  43.06,
        126.02,  15.65,  42.  ,  38.03, 120.99,  10.62,  36.97,  82.96,
         27.41,   1.06, 110.37,  84.02,  26.35]
ar = [2.87, 3.71, 4.16, 4.28, 4.56, 5.41, 1.29, 1.45, 1.49, 1.59, 1.88, 1.12, 1.15, 1.23, 1.46, 1.03, 1.1, 1.3, 1.07, 1.26, 1.19]

In [231]:
len(aa)

21

In [232]:
br = (ratios_test==ar).sum(1)

In [233]:
br

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0])

In [234]:

matching_ratios = ((ratios_test + 0.1) >= ar) * (ratios_test - 0.1 <= ar)

In [235]:
matching_ratios.sum(1)

array([10,  7,  6,  2,  7,  4,  6,  6, 11, 10,  6,  1,  4,  5,  2,  3,  6,
        4,  7,  2,  6,  3,  4,  8,  2,  2,  4,  3,  4,  8,  7,  9,  2])

In [236]:
matching_angles = ((angles_test + 5) >= angles) * (angles_test - 5 <= angles)

In [237]:
matching_angles.sum(1)

array([0, 0, 1, 1, 1, 1, 2, 0, 1, 2, 1, 1, 2, 1, 1, 2, 0, 1, 3, 1, 4, 0,
       1, 1, 0, 6, 1, 1, 0, 1, 1, 1, 4])

In [238]:
matches = ((matching_ratios * ratios_test) * (matching_angles * angles_test) > 0).sum(1)

In [247]:
len(matches)

33

In [240]:
ratios_test

array([[1.15, 1.43, 1.48, 1.61, 1.85, 1.91, 1.25, 1.28, 1.4 , 1.61, 1.66,
        1.03, 1.12, 1.29, 1.33, 1.09, 1.25, 1.29, 1.15, 1.19, 1.03],
       [2.17, 2.83, 3.12, 3.55, 4.63, 5.37, 1.3 , 1.43, 1.63, 2.13, 2.47,
        1.1 , 1.25, 1.63, 1.89, 1.14, 1.48, 1.72, 1.3 , 1.51, 1.16],
       [1.77, 4.08, 4.16, 4.5 , 5.08, 7.  , 2.3 , 2.35, 2.54, 2.87, 3.95,
        1.02, 1.1 , 1.25, 1.72, 1.08, 1.22, 1.68, 1.13, 1.55, 1.38],
       [1.14, 3.16, 3.78, 4.03, 4.88, 6.46, 2.77, 3.32, 3.53, 4.28, 5.67,
        1.2 , 1.28, 1.55, 2.05, 1.07, 1.29, 1.71, 1.21, 1.61, 1.32],
       [1.09, 1.18, 1.41, 1.45, 1.75, 1.81, 1.09, 1.29, 1.33, 1.61, 1.67,
        1.19, 1.22, 1.48, 1.53, 1.03, 1.25, 1.29, 1.21, 1.25, 1.04],
       [1.55, 2.53, 3.01, 4.16, 4.68, 5.19, 1.63, 1.94, 2.67, 3.01, 3.34,
        1.19, 1.64, 1.85, 2.05, 1.38, 1.55, 1.72, 1.13, 1.25, 1.11],
       [1.07, 1.85, 2.22, 2.37, 2.41, 2.54, 1.72, 2.07, 2.2 , 2.24, 2.37,
        1.2 , 1.28, 1.3 , 1.38, 1.07, 1.09, 1.15, 1.02, 1.08, 1.05],

In [241]:
matching_ratios*ratios_test

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.25, 0.  , 1.4 , 1.61, 0.  ,
        1.03, 1.12, 1.29, 0.  , 1.09, 0.  , 1.29, 1.15, 1.19, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 4.63, 5.37, 1.3 , 1.43, 0.  , 0.  , 0.  ,
        1.1 , 1.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.16],
       [0.  , 0.  , 4.16, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        1.02, 1.1 , 1.25, 0.  , 1.08, 0.  , 0.  , 1.13, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        1.2 , 0.  , 0.  , 0.  , 1.07, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.61, 0.  ,
        1.19, 1.22, 0.  , 1.53, 1.03, 0.  , 1.29, 0.  , 1.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        1.19, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.13, 1.25, 1.11],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        1.2 , 0.  , 1.3 , 1.38, 1.07, 1.09, 0.  , 1.02, 0.  , 0.  ],

In [242]:
for i, (m, [ratios, angles]) in enumerate(feature1.items()):
    print(ratios)

[2.87, 3.71, 4.16, 4.28, 4.56, 5.41, 1.29, 1.45, 1.49, 1.59, 1.88, 1.12, 1.15, 1.23, 1.46, 1.03, 1.1, 1.3, 1.07, 1.26, 1.19]
[2.05, 2.93, 3.91, 3.97, 5.01, 5.17, 1.43, 1.9, 1.93, 2.44, 2.52, 1.33, 1.35, 1.71, 1.76, 1.01, 1.28, 1.32, 1.26, 1.3, 1.03]
[1.97, 2.39, 2.47, 2.57, 2.82, 2.94, 1.22, 1.26, 1.31, 1.43, 1.5, 1.03, 1.07, 1.18, 1.23, 1.04, 1.14, 1.19, 1.1, 1.15, 1.04]
[2.2, 2.32, 3.21, 3.24, 3.38, 4.29, 1.05, 1.46, 1.47, 1.53, 1.94, 1.39, 1.4, 1.46, 1.85, 1.01, 1.05, 1.33, 1.04, 1.32, 1.27]
[1.29, 2.39, 2.93, 3.31, 3.74, 4.19, 1.86, 2.28, 2.57, 2.9, 3.26, 1.23, 1.39, 1.56, 1.75, 1.13, 1.27, 1.43, 1.13, 1.27, 1.12]
[1.61, 1.93, 2.43, 2.49, 2.6, 2.71, 1.19, 1.51, 1.54, 1.61, 1.68, 1.26, 1.29, 1.35, 1.41, 1.02, 1.07, 1.11, 1.05, 1.09, 1.04]
[1.01, 1.73, 1.86, 2.14, 3.25, 3.46, 1.71, 1.84, 2.12, 3.22, 3.43, 1.08, 1.24, 1.88, 2.0, 1.15, 1.75, 1.86, 1.52, 1.62, 1.06]
[1.87, 2.34, 2.51, 2.65, 3.0, 3.45, 1.25, 1.34, 1.41, 1.6, 1.84, 1.07, 1.13, 1.28, 1.47, 1.06, 1.19, 1.37, 1.13, 1.3, 1.15

In [243]:
len(ratios_test)

33

In [244]:
len(feature1)

35

In [245]:
# common_points_base, common_points_test = match_tuples(feature1, feature2, th_range = 0.1,th_angle=1.5)

In [246]:
# print(similarity_two_img(len(common_points_base), feature1, feature2))